


<?php $dcode_chapter = $found_chapter; ?>


<!-- form for decoding gregorian to 13 moon -->

<tr>
		<td colspan=2><?php echo "$tr_txt_cubenum"; ?></td>
</tr>
<tr>

		<td class=decode_form_pad_cell></td>

		<td>
	
			<select name="dcode_chapter">
<option value="0"<?php if ($dcode_chapter == "0") echo " SELECTED";?>>0</option>
<option value="1"<?php if ($dcode_chapter == "1") echo " SELECTED";?>>1</option>
<option value="2"<?php if ($dcode_chapter == "2") echo " SELECTED";?>>2</option>
<option value="3"<?php if ($dcode_chapter == "3") echo " SELECTED";?>>3</option>
<option value="4"<?php if ($dcode_chapter == "4") echo " SELECTED";?>>4</option>
<option value="5"<?php if ($dcode_chapter == "5") echo " SELECTED";?>>5</option>
<option value="6"<?php if ($dcode_chapter == "6") echo " SELECTED";?>>6</option>
<option value="7"<?php if ($dcode_chapter == "7") echo " SELECTED";?>>7</option>
<option value="8"<?php if ($dcode_chapter == "8") echo " SELECTED";?>>8</option>
<option value="9"<?php if ($dcode_chapter == "9") echo " SELECTED";?>>9</option>
<option value="10"<?php if ($dcode_chapter == "10") echo " SELECTED";?>>10</option>
<option value="11"<?php if ($dcode_chapter == "11") echo " SELECTED";?>>11</option>
<option value="12"<?php if ($dcode_chapter == "12") echo " SELECTED";?>>12</option>
<option value="13"<?php if ($dcode_chapter == "13") echo " SELECTED";?>>13</option>
<option value="14"<?php if ($dcode_chapter == "14") echo " SELECTED";?>>14</option>
<option value="15"<?php if ($dcode_chapter == "15") echo " SELECTED";?>>15</option>
<option value="16"<?php if ($dcode_chapter == "16") echo " SELECTED";?>>16</option>
<option value="17"<?php if ($dcode_chapter == "17") echo " SELECTED";?>>17</option>
<option value="18"<?php if ($dcode_chapter == "18") echo " SELECTED";?>>18</option>
<option value="19"<?php if ($dcode_chapter == "19") echo " SELECTED";?>>19</option>
<option value="20"<?php if ($dcode_chapter == "20") echo " SELECTED";?>>20</option>
<option value="21"<?php if ($dcode_chapter == "21") echo " SELECTED";?>>21</option>
<option value="22"<?php if ($dcode_chapter == "22") echo " SELECTED";?>>22</option>
<option value="23"<?php if ($dcode_chapter == "23") echo " SELECTED";?>>23</option>
<option value="24"<?php if ($dcode_chapter == "24") echo " SELECTED";?>>24</option>
<option value="25"<?php if ($dcode_chapter == "25") echo " SELECTED";?>>25</option>
<option value="26"<?php if ($dcode_chapter == "26") echo " SELECTED";?>>26</option>
<option value="27"<?php if ($dcode_chapter == "27") echo " SELECTED";?>>27</option>
<option value="28"<?php if ($dcode_chapter == "28") echo " SELECTED";?>>28</option>
<option value="29"<?php if ($dcode_chapter == "29") echo " SELECTED";?>>29</option>
<option value="30"<?php if ($dcode_chapter == "30") echo " SELECTED";?>>30</option>
<option value="31"<?php if ($dcode_chapter == "31") echo " SELECTED";?>>31</option>
<option value="32"<?php if ($dcode_chapter == "32") echo " SELECTED";?>>32</option>
<option value="33"<?php if ($dcode_chapter == "33") echo " SELECTED";?>>33</option>
<option value="34"<?php if ($dcode_chapter == "34") echo " SELECTED";?>>34</option>
<option value="35"<?php if ($dcode_chapter == "35") echo " SELECTED";?>>35</option>
<option value="36"<?php if ($dcode_chapter == "36") echo " SELECTED";?>>36</option>
<option value="37"<?php if ($dcode_chapter == "37") echo " SELECTED";?>>37</option>
<option value="38"<?php if ($dcode_chapter == "38") echo " SELECTED";?>>38</option>
<option value="39"<?php if ($dcode_chapter == "39") echo " SELECTED";?>>39</option>
<option value="40"<?php if ($dcode_chapter == "40") echo " SELECTED";?>>40</option>
<option value="41"<?php if ($dcode_chapter == "41") echo " SELECTED";?>>41</option>
<option value="42"<?php if ($dcode_chapter == "42") echo " SELECTED";?>>42</option>
<option value="43"<?php if ($dcode_chapter == "43") echo " SELECTED";?>>43</option>
<option value="44"<?php if ($dcode_chapter == "44") echo " SELECTED";?>>44</option>
<option value="45"<?php if ($dcode_chapter == "45") echo " SELECTED";?>>45</option>
<option value="46"<?php if ($dcode_chapter == "46") echo " SELECTED";?>>46</option>
<option value="47"<?php if ($dcode_chapter == "47") echo " SELECTED";?>>47</option>
<option value="48"<?php if ($dcode_chapter == "48") echo " SELECTED";?>>48</option>
<option value="49"<?php if ($dcode_chapter == "49") echo " SELECTED";?>>49</option>
<option value="50"<?php if ($dcode_chapter == "50") echo " SELECTED";?>>50</option>
<option value="51"<?php if ($dcode_chapter == "51") echo " SELECTED";?>>51</option>
<option value="52"<?php if ($dcode_chapter == "52") echo " SELECTED";?>>52</option>
<option value="53"<?php if ($dcode_chapter == "53") echo " SELECTED";?>>53</option>
<option value="54"<?php if ($dcode_chapter == "54") echo " SELECTED";?>>54</option>
<option value="55"<?php if ($dcode_chapter == "55") echo " SELECTED";?>>55</option>
<option value="56"<?php if ($dcode_chapter == "56") echo " SELECTED";?>>56</option>
<option value="57"<?php if ($dcode_chapter == "57") echo " SELECTED";?>>57</option>
<option value="58"<?php if ($dcode_chapter == "58") echo " SELECTED";?>>58</option>
<option value="59"<?php if ($dcode_chapter == "59") echo " SELECTED";?>>59</option>
<option value="60"<?php if ($dcode_chapter == "60") echo " SELECTED";?>>60</option>
<option value="61"<?php if ($dcode_chapter == "61") echo " SELECTED";?>>61</option>
<option value="62"<?php if ($dcode_chapter == "62") echo " SELECTED";?>>62</option>
<option value="63"<?php if ($dcode_chapter == "63") echo " SELECTED";?>>63</option>
<option value="64"<?php if ($dcode_chapter == "64") echo " SELECTED";?>>64</option>

			</select>
		</td>

		<td>
			<input type=submit value="#" style="padding-top: 2px; padding-right: 2px; padding-bottom: 2px; padding-left: 2px;" title="Choose any uChing chapter and click here to de-code">

		</td>

